name: publish

on:
  push:
    tags:
      - 'core@[0-9]+\.[0-9]+\.[0-9]+'
      - 'core@[0-9]+\.[0-9]+\.[0-9]+-rc'
      - 'solvers@[0-9]+\.[0-9]+\.[0-9]+'
      - 'solvers@[0-9]+\.[0-9]+\.[0-9]+-rc'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          echo "PACKAGE_NAME=$(echo ${{ github.ref_name }} | cut -d'@' -f1)" >> $GITHUB_ENV
          echo "STAGE=${{ endsWith(github.ref_name, 'rc') && 'preview' || 'live' }}" >> $$GITHUB_ENV
      - run: |
          pipx install poetry
          cd ${{ env.PACKAGE_NAME }}
          poetry install
          poetry build
      - uses: actions/upload-artifact@v4
        with:
          name: 'distribution'
          path: '${{ env.PACKAGE_NAME }}/dist/'
          if-no-files-found: error

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: 'distribution'
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ env.STAGE == 'preview' && 'https://test.pypi.org/legacy/' || 'https://pypi.org/simple/' }}
          verbose: true
