name: Lint

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: >-
            experiments/
            core/
            solvers/
      - run: ruff check --fix --exclude archived_code
      - run: ruff format --diff
