name: build

on: [push]

jobs:
  build_solvers:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
#          - os: macos-13  # Intel
#            cibw_archs: "x86_64"
#          - os: macos-14  # Apple Silicon
#            cibw_archs: "arm64"
          - os: ubuntu-latest
            cibw_archs: "auto"
#          - os: windows-latest
#            cibw_archs: "auto"

    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        with:
          package-dir: solvers
        env:
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
      - run: |
          ls -l
          ls -R wheelhouse/
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
